// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cats.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCatsByOwner = `-- name: CountCatsByOwner :one
SELECT COUNT(*)
FROM cats
WHERE owner_id = $1
AND deleted_at IS NULL
`

func (q *Queries) CountCatsByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCatsByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCat = `-- name: CreateCat :one
INSERT INTO cats (
  owner_id,
  name,
  breed,
  date_of_birth,
  weight,
  color,
  gender,
  photo_url,
  medical_notes,
  dietary_requirements
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, owner_id, name, breed, date_of_birth, weight, color, gender, photo_url, medical_notes, dietary_requirements, date_of_death, created_at, updated_at, deleted_at
`

type CreateCatParams struct {
	OwnerID             uuid.UUID      `json:"owner_id"`
	Name                string         `json:"name"`
	Breed               *string        `json:"breed"`
	DateOfBirth         pgtype.Date    `json:"date_of_birth"`
	Weight              pgtype.Numeric `json:"weight"`
	Color               *string        `json:"color"`
	Gender              *string        `json:"gender"`
	PhotoUrl            *string        `json:"photo_url"`
	MedicalNotes        *string        `json:"medical_notes"`
	DietaryRequirements *string        `json:"dietary_requirements"`
}

func (q *Queries) CreateCat(ctx context.Context, arg CreateCatParams) (Cat, error) {
	row := q.db.QueryRow(ctx, createCat,
		arg.OwnerID,
		arg.Name,
		arg.Breed,
		arg.DateOfBirth,
		arg.Weight,
		arg.Color,
		arg.Gender,
		arg.PhotoUrl,
		arg.MedicalNotes,
		arg.DietaryRequirements,
	)
	var i Cat
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Breed,
		&i.DateOfBirth,
		&i.Weight,
		&i.Color,
		&i.Gender,
		&i.PhotoUrl,
		&i.MedicalNotes,
		&i.DietaryRequirements,
		&i.DateOfDeath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCatByID = `-- name: GetCatByID :one
SELECT id, owner_id, name, breed, date_of_birth, weight, color, gender, photo_url, medical_notes, dietary_requirements, date_of_death, created_at, updated_at, deleted_at FROM cats
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetCatByID(ctx context.Context, id uuid.UUID) (Cat, error) {
	row := q.db.QueryRow(ctx, getCatByID, id)
	var i Cat
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Breed,
		&i.DateOfBirth,
		&i.Weight,
		&i.Color,
		&i.Gender,
		&i.PhotoUrl,
		&i.MedicalNotes,
		&i.DietaryRequirements,
		&i.DateOfDeath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCatOwner = `-- name: GetCatOwner :one
SELECT owner_id
FROM cats
WHERE id = $1
`

func (q *Queries) GetCatOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCatOwner, id)
	var owner_id uuid.UUID
	err := row.Scan(&owner_id)
	return owner_id, err
}

const listCatsByOwner = `-- name: ListCatsByOwner :many
SELECT id, owner_id, name, breed, date_of_birth, weight, color, gender, photo_url, medical_notes, dietary_requirements, date_of_death, created_at, updated_at, deleted_at FROM cats
WHERE owner_id = $1
AND deleted_at IS NULL
`

func (q *Queries) ListCatsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Cat, error) {
	rows, err := q.db.Query(ctx, listCatsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cat{}
	for rows.Next() {
		var i Cat
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Breed,
			&i.DateOfBirth,
			&i.Weight,
			&i.Color,
			&i.Gender,
			&i.PhotoUrl,
			&i.MedicalNotes,
			&i.DietaryRequirements,
			&i.DateOfDeath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCatsDeath = `-- name: MarkCatsDeath :exec
UPDATE cats
SET date_of_death = $1
WHERE id = $2
AND owner_id = $3
AND deleted_at IS NULL
`

type MarkCatsDeathParams struct {
	DateOfDeath pgtype.Date `json:"date_of_death"`
	ID          uuid.UUID   `json:"id"`
	OwnerID     uuid.UUID   `json:"owner_id"`
}

func (q *Queries) MarkCatsDeath(ctx context.Context, arg MarkCatsDeathParams) error {
	_, err := q.db.Exec(ctx, markCatsDeath, arg.DateOfDeath, arg.ID, arg.OwnerID)
	return err
}

const recordCatDeath = `-- name: RecordCatDeath :one
UPDATE cats SET
  date_of_death = $1
WHERE id = $2
AND deleted_at IS NULL
RETURNING id, owner_id, name, breed, date_of_birth, weight, color, gender, photo_url, medical_notes, dietary_requirements, date_of_death, created_at, updated_at, deleted_at
`

type RecordCatDeathParams struct {
	DateOfDeath pgtype.Date `json:"date_of_death"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) RecordCatDeath(ctx context.Context, arg RecordCatDeathParams) (Cat, error) {
	row := q.db.QueryRow(ctx, recordCatDeath, arg.DateOfDeath, arg.ID)
	var i Cat
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Breed,
		&i.DateOfBirth,
		&i.Weight,
		&i.Color,
		&i.Gender,
		&i.PhotoUrl,
		&i.MedicalNotes,
		&i.DietaryRequirements,
		&i.DateOfDeath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteCat = `-- name: SoftDeleteCat :exec
UPDATE cats
SET deleted_at = NOW()
WHERE id = $1
AND owner_id = $2
AND deleted_at IS NULL
`

type SoftDeleteCatParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) SoftDeleteCat(ctx context.Context, arg SoftDeleteCatParams) error {
	_, err := q.db.Exec(ctx, softDeleteCat, arg.ID, arg.OwnerID)
	return err
}

const softDeleteCatsByOwner = `-- name: SoftDeleteCatsByOwner :exec
UPDATE cats
SET deleted_at = NOW()
WHERE owner_id = $1
`

func (q *Queries) SoftDeleteCatsByOwner(ctx context.Context, ownerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCatsByOwner, ownerID)
	return err
}

const updateCat = `-- name: UpdateCat :one
UPDATE cats SET
  name = COALESCE($1, name),
  breed = COALESCE($2, breed),
  date_of_birth = COALESCE($3, date_of_birth),
  weight = COALESCE($4, weight),
  color = COALESCE($5, color),
  gender = COALESCE($6, gender),
  photo_url = COALESCE($7, photo_url),
  medical_notes = COALESCE($8, medical_notes),
  dietary_requirements = COALESCE($9, dietary_requirements),
  updated_at = NOW()
WHERE id = $10
AND owner_id = $11
AND deleted_at IS NULL
RETURNING id, owner_id, name, breed, date_of_birth, weight, color, gender, photo_url, medical_notes, dietary_requirements, date_of_death, created_at, updated_at, deleted_at
`

type UpdateCatParams struct {
	Name                string         `json:"name"`
	Breed               *string        `json:"breed"`
	DateOfBirth         pgtype.Date    `json:"date_of_birth"`
	Weight              pgtype.Numeric `json:"weight"`
	Color               *string        `json:"color"`
	Gender              *string        `json:"gender"`
	PhotoUrl            *string        `json:"photo_url"`
	MedicalNotes        *string        `json:"medical_notes"`
	DietaryRequirements *string        `json:"dietary_requirements"`
	ID                  uuid.UUID      `json:"id"`
	OwnerID             uuid.UUID      `json:"owner_id"`
}

func (q *Queries) UpdateCat(ctx context.Context, arg UpdateCatParams) (Cat, error) {
	row := q.db.QueryRow(ctx, updateCat,
		arg.Name,
		arg.Breed,
		arg.DateOfBirth,
		arg.Weight,
		arg.Color,
		arg.Gender,
		arg.PhotoUrl,
		arg.MedicalNotes,
		arg.DietaryRequirements,
		arg.ID,
		arg.OwnerID,
	)
	var i Cat
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Breed,
		&i.DateOfBirth,
		&i.Weight,
		&i.Color,
		&i.Gender,
		&i.PhotoUrl,
		&i.MedicalNotes,
		&i.DietaryRequirements,
		&i.DateOfDeath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCatPhoto = `-- name: UpdateCatPhoto :one
UPDATE cats SET
  photo_url = $1,
  updated_at = NOW()
WHERE id = $2
AND owner_id = $3
AND deleted_at IS NULL
RETURNING id, owner_id, name, breed, date_of_birth, weight, color, gender, photo_url, medical_notes, dietary_requirements, date_of_death, created_at, updated_at, deleted_at
`

type UpdateCatPhotoParams struct {
	PhotoUrl *string   `json:"photo_url"`
	ID       uuid.UUID `json:"id"`
	OwnerID  uuid.UUID `json:"owner_id"`
}

func (q *Queries) UpdateCatPhoto(ctx context.Context, arg UpdateCatPhotoParams) (Cat, error) {
	row := q.db.QueryRow(ctx, updateCatPhoto, arg.PhotoUrl, arg.ID, arg.OwnerID)
	var i Cat
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Breed,
		&i.DateOfBirth,
		&i.Weight,
		&i.Color,
		&i.Gender,
		&i.PhotoUrl,
		&i.MedicalNotes,
		&i.DietaryRequirements,
		&i.DateOfDeath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
