// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Cat struct {
	ID                  uuid.UUID      `json:"id"`
	OwnerID             uuid.UUID      `json:"owner_id"`
	Name                string         `json:"name"`
	Breed               pgtype.Text    `json:"breed"`
	DateOfBirth         pgtype.Date    `json:"date_of_birth"`
	Weight              pgtype.Numeric `json:"weight"`
	Color               pgtype.Text    `json:"color"`
	Gender              pgtype.Text    `json:"gender"`
	PhotoUrl            pgtype.Text    `json:"photo_url"`
	MedicalNotes        pgtype.Text    `json:"medical_notes"`
	DietaryRequirements pgtype.Text    `json:"dietary_requirements"`
	DateOfDeath         pgtype.Date    `json:"date_of_death"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           *time.Time     `json:"deleted_at"`
}
