// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountCatsByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error)
	CreateCat(ctx context.Context, arg CreateCatParams) (Cat, error)
	GetCatByID(ctx context.Context, id uuid.UUID) (Cat, error)
	GetCatOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	ListCatsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Cat, error)
	MarkCatsDeath(ctx context.Context, arg MarkCatsDeathParams) error
	RecordCatDeath(ctx context.Context, arg RecordCatDeathParams) (Cat, error)
	SoftDeleteCat(ctx context.Context, arg SoftDeleteCatParams) error
	SoftDeleteCatsByOwner(ctx context.Context, ownerID uuid.UUID) error
	UpdateCat(ctx context.Context, arg UpdateCatParams) (Cat, error)
	UpdateCatPhoto(ctx context.Context, arg UpdateCatPhotoParams) (Cat, error)
}

var _ Querier = (*Queries)(nil)
